apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: mq-event-listener
  namespace: mq
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          name: github-push-binding
      template:
        name: mq-trigger-template
