apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: generate-bar
  namespace: ace
spec:
  params:
    - default: getHello
      description: Specify the name of the project being built.
      name: project
      type: string
  resources:
    - name: source
      type: git
  tasks:
    - name: generate-bar-task
      params:
        - name: project
          value: $(params.project)
      resources:
        inputs:
          - name: source
            resource: source
      taskRef:
        kind: Task
        name: generate-bar
