apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ace-event-listener
  namespace: ace
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          name: github-push-binding
      template:
        name: ace-trigger-template
