apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-ace-image
  namespace: ace
spec:
  params:
    - default: ace
      description: Specify the name of the project being built.
      name: project
      type: string
    - default: 'quay.io/buildah/stable:v1.11.0'
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: .
      description: Path to the directory to use as context.
      name: CONTEXT
      type: string
    - default: 'false'
      description: >-
        Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      name: TLSVERIFY
      type: string
    - default: ./ace-simple-flow/getHello/Dockerfile
      description: Path to the Dockerfile to build.
      name: dockerfileLocation
      type: string
  resources:
    inputs:
      - name: cp4i-component-source
        type: git
    outputs:
      - name: image
        type: image
  steps:
    - args:
        - '-c'
        - |
          set -e

          git fetch --unshallow

          echo COMMIT_COUNT=`git rev-list --count HEAD` >> ./env-config

          cp ./env-config /var/lib/containers

          cd ..

          ls -R
      command:
        - /bin/sh
      image: alpine/git
      name: create-image-tage
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/cp4i-component-source
    - resources: {}
      name: build-image
      command:
        - /bin/bash
      env:
        - name: PROJECT
          value: $(inputs.params.project)
        - name: ARTIFACTORY_USER
          valueFrom:
            secretKeyRef:
              key: ARTIFACTORY_USER
              name: artifactory-credentials
        - name: ARTIFACTORY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ARTIFACTORY_PASSWORD
              name: artifactory-credentials
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      image: $(inputs.params.BUILDER_IMAGE)
      workingDir: /workspace/cp4i-component-source
      args:
        - '-c'
        - >
          set -e

          . ./env-config

          echo "COMMIT_COUNT: ${COMMIT_COUNT}"

          curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} -O
          "http://159.8.178.163/artifactory/test/${PROJECT}.bar"

          mkdir ./ace-simple-flow/${PROJECT}/gen/ || true

          cp ${PROJECT}.bar ./ace-simple-flow/${PROJECT}/gen/

          buildah bud --tls-verify=$(inputs.params.TLSVERIFY) --layers -f
          $(inputs.params.dockerfileLocation)  -t
          $(outputs.resources.image.url):${COMMIT_COUNT}-amd64
          $(inputs.params.CONTEXT)
    - args:
        - '-c'
        - >
          set -e

          . ./env-config

          buildah push --tls-verify=$(inputs.params.TLSVERIFY)
          "$(outputs.resources.image.url):${COMMIT_COUNT}-amd64"
          "docker://$(outputs.resources.image.url):${COMMIT_COUNT}-amd64"
      command:
        - /bin/bash
      image: $(inputs.params.BUILDER_IMAGE)
      name: push-image
      resources: {}
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      workingDir: /workspace/cp4i-component-source
  volumes:
    - emptyDir: {}
      name: varlibcontainers
