apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: generate-bar
spec:
  params:
    - name: project
      type: string
    - name: artifactoryRepo
      type: string
    - name: flowDirectory
      type: string
  resources:
    inputs:
      - name: cp4i-component-source
        type: git
  steps:
    - args:
        - "-c"
        - >
          set -eu;

          echo Project : $PROJECT;

          /usr/bin/Xvfb :100 & 

          export DISPLAY=:100   

          mqsicreatebar -data . -b ${PROJECT}.bar -a ${PROJECT} -trace

          # Push the bar file to artifactory

          curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} -T ${PROJECT}.bar
          "${ARTIFACTORY_URL}/artifactory/$(inputs.params.artifactoryRepo)/${PROJECT}.bar"

          # Push the generated msgflow to artifactory

          curl -u ${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} -T
          ./${PROJECT}/gen/${PROJECT}.msgflow
          "${ARTIFACTORY_URL}/artifactory/$(inputs.params.artifactoryRepo)/${PROJECT}.msgflow"
      command:
        - /bin/sh
      env:
        - name: PROJECT
          value: $(inputs.params.project)
        - name: ARTIFACTORY_USER
          valueFrom:
            secretKeyRef:
              key: ARTIFACTORY_USER
              name: artifactory-credentials
        - name: ARTIFACTORY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ARTIFACTORY_PASSWORD
              name: artifactory-credentials
        - name: ARTIFACTORY_URL
          valueFrom:
            secretKeyRef:
              key: ARTIFACTORY_URL
              name: artifactory-credentials
      image: docker.io/rsundara/ace-build
      name: compile
      resources: {}
      workingDir: /workspace/cp4i-component-source/$(inputs.params.flowDirectory)
