apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: deploy-to-ucd
spec:
  params:
    - default: "docker.io/node:10-stretch"
      name: js-image
      type: string
    - default: "quay.io/buildah/stable:v1.11.0"
      name: BUILDER_IMAGE
      type: string
    - default: ./Dockerfile
      name: DOCKERFILE
      type: string
    - default: .
      name: CONTEXT
      type: string
    - default: "false"
      name: TLSVERIFY
      type: string
    - name: ucd-url
      type: string
    - default: "443"
      name: ucd-port
      type: string
    - default: DEV
      name: environment
      type: string
    - default: Deploy from YAML file
      name: applicationProcess
      type: string
    - name: component-name
      type: string
    - name: application-name
      type: string
    - name: helm-release-name
      type: string
  resources:
    inputs:
      - name: cp4i-component-source
        type: git
      - name: script-source
        type: git
  steps:
    - resources: {}
      name: deploy-to-ucd
      command:
        - /bin/bash
      env:
        - name: UCD_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: ucd-credentials
              optional: true
        - name: UCD_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: ucd-credentials
              optional: true
        - name: UCD_URL
          value: $(inputs.params.ucd-url)
        - name: UCD_PORT
          value: $(inputs.params.ucd-port)
        - name: COMPONENT_NAME
          value: $(inputs.params.component-name)
        - name: APPLICATION_NAME
          value: $(inputs.params.application-name)
        - name: APPLICATION_PROCESS
          value: deploy
        - name: ENV
          value: dev
        - name: HELM_RELEASE_NAME
          value: $(inputs.params.helm-release-name)
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
      image: ellerbrock/alpine-bash-curl-ssl
      workingDir: /workspace/script-source
      args:
        - "-c"
        - |
          set -e

          . /workspace/persistent/env-config

          echo "TIME_STAMP: ${TIME_STAMP}"

          export SNAPSHOT_ID=$TIME_STAMP
          #imagetag
          export COMPONENT_VERSION=$TIME_STAMP

          sh ./utils/deploy-via-UCD.sh
  volumes:
    - emptyDir: {}
      name: varlibcontainers
  workspaces:
    - name: persistent
