apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: build-custom-mq-image
  namespace: mq
spec:
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/mq/mq-custom-image'
  type: image
