apiVersion: v1
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.ibm.com
  labels:
    serviceAccount: pipeline
  name: git-secret
data:
  password: <personal-access-token-in-base64>
  username: <user-name-in-base64>
type: kubernetes.io/basic-auth